//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class feedbacks
    {
        public int feedback_id { get; set; }
        public int user_id { get; set; }
        public int product_id { get; set; }
        public string content { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual users users { get; set; }
    }
}
