//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int user_id { get; set; }
        public string email { get; set; }
        public string name_Student { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public string payment_method { get; set; }
        public string status { get; set; }
    
        public virtual users users { get; set; }
    }
}
